version: '2'

services:
  nginx:
    image: nginx:1.15.0
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src:/var/www/html
    ports:
      - 80:80
  php:
    image: "php:${PHP_VERSION}-fpm"
    volumes:
      - ../src:/var/www/html